export const featureList = [
    {
        name : 'No of surveys',
        starter : 'Unlimited',
        plus : 'Unlimited',
        business : 'Unlimited',
    },
    {
        name : 'Simultaneous active surveys',
        starter : '3',
        plus : '5',
        business : '10',
    },
    {
        name : 'Users',
        starter : '1',
        plus : '3',
        business : '10',
    },
    {
        name : 'Included monthly responses',
        starter : '100',
        plus : '2000',
        business : '10000',
    },
    {
        name : 'Workspace',
        starter : '1',
        plus : '1',
        business : '1',
    },
    {
        name : 'NPS Date & Other question type',
        starter : 'yes',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Skip Logic',
        starter : 'yes',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Multiple endings',
        starter : 'yes',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Standard support',
        starter : 'yes',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Download data',
        starter : 'yes',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Completion rate',
        starter : 'yes',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Templates',
        starter : 'yes',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Email notification',
        starter : 'yes',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : '48 hour SLA response time',
        starter : 'yes',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : '24 Hour SLA response time',
        starter : 'no',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Custom data filters',
        starter : 'no',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Notify respondents automatically by email when they submit a response',
        starter : 'no',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Redirect respondents to a custom URL when they submit a response',
        starter : 'no',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Add company logo',
        starter : 'no',
        plus : 'yes',
        business : 'yes',
    },
    {
        name : 'Brand removal',
        starter : 'no',
        plus : 'no',
        business : 'yes',
    },
    {
        name : 'Custom thank you screen',
        starter : 'no',
        plus : 'no',
        business : 'yes',
    },
    {
        name : 'Word cloud',
        starter : 'no',
        plus : 'no',
        business : 'yes',
    },
    {
        name : 'Redirect from ending screen',
        starter : 'no',
        plus : 'no',
        business : 'yes',
    },
    {
        name : 'Priority support',
        starter : 'no',
        plus : 'no',
        business : 'yes',
    },
    {
        name : 'Teammate roles',
        starter : 'no',
        plus : 'no',
        business : 'yes',
    },
]